name: C++ CI Build

on:
  push:
    branches: [ main ] # Runs on pushes to the main branch
  pull_request:
    branches: [ main ] # Optional: Also runs on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libreadline-dev

      # Configure the project using CMake
      # Note: We probably don't need CMAKE_PREFIX_PATH or PKG_CONFIG_PATH here
      # because apt-get installs libs/headers/pc files in standard system locations.
      - name: Configure CMake
        run: cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release # Build in Release mode for CI

      # Build the project
      - name: Build
        run: cmake --build ${{github.workspace}}/build
