name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache CMake dependencies
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: cmake-deps-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-deps-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libreadline-dev

      - name: Install LLVM/Clang 20 tools
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20 all # 'all' installs all tools
          clang-format-20 --version

          # Symlink clang-format-20 to clang-format
          sudo ln -sf /usr/bin/clang-format-20 /usr/bin/clang-format
          clang-format --version

      - name: Validate Formatting
        run: |
          find src include tests -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -print0 | \
          xargs -0 clang-format --dry-run -Werror

      # Configure the project using CMake
      # Note: We probably don't need CMAKE_PREFIX_PATH or PKG_CONFIG_PATH here
      # because apt-get installs libs/headers/pc files in standard system locations.
      - name: Configure CMake
        run: cmake . -B ${{github.workspace}}/build

      # Build the project
      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure --parallel
